# Generated by Django 4.1.3 on 2023-01-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='id_question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='id_category',
        ),
        migrations.AddField(
            model_name='answer',
            name='question_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_pk', to='Polls_and_surveys.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Sub_Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('category_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_pk', to='Polls_and_surveys.categorie')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='sub_category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_pk', to='Polls_and_surveys.sub_categorie'),
        ),
    ]
