# Generated by Django 4.1.3 on 2023-01-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0002_rename_category_categorie_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
