# Generated by Django 4.1.3 on 2023-01-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0005_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Polls_and_surveys.sub_categorie'),
        ),
    ]
