# Generated by Django 4.1.3 on 2023-02-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0006_alter_score_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='question',
            new_name='sub_Categorie_id',
        ),
    ]
