# Generated by Django 4.1.3 on 2023-02-02 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0007_rename_question_score_sub_categorie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='sub_Categorie_id',
            new_name='sub_categorie_id',
        ),
    ]
