# Generated by Django 4.1.3 on 2023-02-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0008_rename_sub_categorie_id_score_sub_categorie_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='sub_categorie_id',
        ),
    ]
