# Generated by Django 4.1.3 on 2023-02-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0009_remove_score_sub_categorie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
