# Generated by Django 4.1.3 on 2023-02-03 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0010_alter_score_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='create_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz', to='Polls_and_surveys.myuser'),
        ),
    ]
