# Generated by Django 4.1.3 on 2023-02-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0011_question_create_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='create_by',
        ),
        migrations.CreateModel(
            name='MyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('answer', models.BooleanField(default=False)),
                ('explication', models.TextField(blank=True, default='', null=True)),
                ('create_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quiz', to='Polls_and_surveys.myuser')),
            ],
        ),
    ]
