# Generated by Django 4.1.3 on 2023-02-03 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0012_remove_question_create_by_myquiz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myquiz',
            old_name='question',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='myquiz',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='myquiz',
            name='explication',
        ),
        migrations.RemoveField(
            model_name='myquiz',
            name='picture',
        ),
        migrations.CreateModel(
            name='MyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('picture', models.ImageField(upload_to='')),
                ('answer', models.BooleanField(default=False)),
                ('explication', models.TextField(blank=True, default='', null=True)),
                ('quiz', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myquiz', to='Polls_and_surveys.myquiz')),
            ],
        ),
    ]
