# Generated by Django 4.1.3 on 2023-02-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0013_rename_question_myquiz_name_remove_myquiz_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myquiz',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myquestion',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
