# Generated by Django 4.1.3 on 2023-02-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0015_alter_myquiz_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myquestion',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='myquiz',
            name='picture',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
