# Generated by Django 4.1.3 on 2023-02-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Polls_and_surveys', '0016_alter_myquestion_picture_alter_myquiz_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='media/img/'),
        ),
        migrations.AlterField(
            model_name='myquestion',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='media/img/'),
        ),
        migrations.AlterField(
            model_name='myquiz',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='media/img/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='media/img/'),
        ),
        migrations.AlterField(
            model_name='sub_categorie',
            name='picture',
            field=models.ImageField(default=None, null=True, upload_to='media/img/'),
        ),
    ]
